create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text unique,
  full_name text,
  role text not null default 'operator' check (role in ('operator', 'supervisor', 'manager', 'admin')),
  is_active boolean not null default true,
  is_approved boolean not null default false,
  approved_at timestamptz,
  approved_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sites (
  id bigint generated by default as identity primary key,
  name text not null unique,
  type text not null check (type in ('CHLORINATION', 'DEEPWELL')),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.site_assignments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  site_id bigint not null references public.sites (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, site_id)
);

create table if not exists public.readings (
  id uuid primary key default gen_random_uuid(),
  site_id bigint not null references public.sites (id) on delete restrict,
  submitted_by uuid not null references public.profiles (id) on delete restrict,
  site_type text not null check (site_type in ('CHLORINATION', 'DEEPWELL')),
  reading_datetime timestamptz not null,
  slot_datetime timestamptz not null,
  status text not null default 'submitted' check (status in ('submitted', 'approved', 'rejected')),
  remarks text,
  totalizer numeric,
  pressure_psi numeric,
  rc_ppm numeric,
  turbidity_ntu numeric,
  ph numeric,
  tds_ppm numeric,
  tank_level_liters numeric,
  flowrate_m3hr numeric,
  chlorine_consumed numeric,
  upstream_pressure_psi numeric,
  downstream_pressure_psi numeric,
  vfd_frequency_hz numeric,
  voltage_l1_v numeric,
  voltage_l2_v numeric,
  voltage_l3_v numeric,
  amperage_a numeric,
  power_kwh_shift numeric,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists readings_site_slot_unique
on public.readings (site_id, slot_datetime);

create table if not exists public.reading_audit_log (
  id uuid primary key default gen_random_uuid(),
  reading_id uuid not null references public.readings (id) on delete cascade,
  actor_user_id uuid references public.profiles (id) on delete set null,
  action text not null,
  before_json jsonb,
  after_json jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function public.protect_profile_admin_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() = old.id and coalesce(public.current_role(), 'operator') not in ('admin', 'supervisor', 'manager') then
    if new.role is distinct from old.role
      or new.is_active is distinct from old.is_active
      or new.is_approved is distinct from old.is_approved
      or new.approved_at is distinct from old.approved_at
      or new.approved_by is distinct from old.approved_by then
      raise exception 'Only a manager, supervisor, or admin can change approval or role fields.';
    end if;
  end if;

  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, ''), '@', 1))
  )
  on conflict (id) do update
  set
    email = excluded.email,
    full_name = coalesce(excluded.full_name, public.profiles.full_name),
    updated_at = timezone('utc', now());

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists profiles_protect_admin_fields on public.profiles;
create trigger profiles_protect_admin_fields
before update on public.profiles
for each row execute procedure public.protect_profile_admin_fields();

drop trigger if exists readings_set_updated_at on public.readings;
create trigger readings_set_updated_at
before update on public.readings
for each row execute procedure public.set_updated_at();

create or replace function public.log_reading_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.reading_audit_log (reading_id, actor_user_id, action, after_json)
    values (new.id, auth.uid(), 'insert', to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    insert into public.reading_audit_log (reading_id, actor_user_id, action, before_json, after_json)
    values (new.id, auth.uid(), 'update', to_jsonb(old), to_jsonb(new));
    return new;
  elsif tg_op = 'DELETE' then
    insert into public.reading_audit_log (reading_id, actor_user_id, action, before_json)
    values (old.id, auth.uid(), 'delete', to_jsonb(old));
    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists readings_audit_trigger on public.readings;
create trigger readings_audit_trigger
after insert or update or delete on public.readings
for each row execute procedure public.log_reading_change();

alter table public.profiles enable row level security;
alter table public.sites enable row level security;
alter table public.site_assignments enable row level security;
alter table public.readings enable row level security;
alter table public.reading_audit_log enable row level security;

create or replace function public.current_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid()
$$;

create or replace function public.is_active_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and is_active = true
  )
$$;

create or replace function public.is_approved_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and is_active = true
      and (
        is_approved = true
        or role in ('supervisor', 'manager', 'admin')
      )
  )
$$;

create or replace function public.is_admin_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and is_active = true
      and role = 'admin'
  )
$$;

create or replace function public.approve_operator_account(target_profile_id uuid)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_profile public.profiles;
begin
  if not public.is_admin_user() then
    raise exception 'Only admins can approve operator accounts.';
  end if;

  update public.profiles
  set
    is_approved = true,
    is_active = true,
    approved_at = timezone('utc', now()),
    approved_by = auth.uid(),
    updated_at = timezone('utc', now())
  where id = target_profile_id
    and role = 'operator'
  returning * into updated_profile;

  if updated_profile.id is null then
    raise exception 'Operator profile not found.';
  end if;

  return updated_profile;
end;
$$;

create or replace function public.assign_profile_role(target_profile_id uuid, next_role text)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_role text := lower(trim(next_role));
  updated_profile public.profiles;
begin
  if not public.is_admin_user() then
    raise exception 'Only admins can assign office roles.';
  end if;

  if target_profile_id = auth.uid() and normalized_role <> 'admin' then
    raise exception 'Admins cannot remove their own admin role from the dashboard.';
  end if;

  if normalized_role not in ('operator', 'supervisor', 'manager', 'admin') then
    raise exception 'Invalid role.';
  end if;

  update public.profiles
  set
    role = normalized_role,
    is_active = true,
    is_approved = case
      when normalized_role = 'operator' then is_approved
      else true
    end,
    approved_at = case
      when normalized_role = 'operator' then approved_at
      else coalesce(approved_at, timezone('utc', now()))
    end,
    approved_by = case
      when normalized_role = 'operator' then approved_by
      else coalesce(approved_by, auth.uid())
    end,
    updated_at = timezone('utc', now())
  where id = target_profile_id
  returning * into updated_profile;

  if updated_profile.id is null then
    raise exception 'Profile not found.';
  end if;

  return updated_profile;
end;
$$;

drop policy if exists "profiles self select" on public.profiles;
create policy "profiles self select"
on public.profiles
for select
using (
  auth.uid() = id
  or public.current_role() in ('admin', 'supervisor', 'manager')
);

drop policy if exists "profiles self upsert" on public.profiles;
create policy "profiles self upsert"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "profiles self update" on public.profiles;
create policy "profiles self update"
on public.profiles
for update
using (auth.uid() = id or public.current_role() = 'admin')
with check (auth.uid() = id or public.current_role() = 'admin');

drop policy if exists "assigned sites select" on public.sites;
create policy "all active users can select sites"
on public.sites
for select
using (
  auth.uid() is not null
  and public.is_approved_user()
);

drop policy if exists "site assignments self select" on public.site_assignments;
create policy "site assignments self select"
on public.site_assignments
for select
using (
  user_id = auth.uid()
  or public.current_role() in ('admin', 'supervisor', 'manager')
);

drop policy if exists "site assignments admin write" on public.site_assignments;
create policy "site assignments admin write"
on public.site_assignments
for all
using (public.current_role() = 'admin')
with check (public.current_role() = 'admin');

drop policy if exists "readings select" on public.readings;
create policy "users can read own readings or elevated roles"
on public.readings
for select
using (
  public.current_role() in ('admin', 'supervisor', 'manager')
  or submitted_by = auth.uid()
);

drop policy if exists "readings insert own assigned sites" on public.readings;
create policy "active users can insert their own readings"
on public.readings
for insert
with check (
  submitted_by = auth.uid()
  and auth.uid() is not null
  and public.is_approved_user()
);

drop policy if exists "readings admin update" on public.readings;
create policy "readings admin update"
on public.readings
for update
using (public.current_role() in ('admin', 'supervisor', 'manager'))
with check (public.current_role() in ('admin', 'supervisor', 'manager'));

drop policy if exists "reading audit visible to supervisors" on public.reading_audit_log;
create policy "reading audit visible to supervisors"
on public.reading_audit_log
for select
using (public.current_role() in ('admin', 'supervisor', 'manager'));

insert into public.sites (name, type)
values
  ('Main Chlorination Facility', 'CHLORINATION'),
  ('Main Deepwell Pump', 'DEEPWELL')
on conflict (name) do nothing;
